server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8083/eureka

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: firstModule
          uri: lb://FIRST-SERVICE
          predicates:
            - Path=/first-service/**
        - id: secondModule
          uri: lb://SECOND-SERVICE
          predicates:
            - Path=/second-service/**