server:
  port: 8081

spring:
  # для регистрации в eureka и cloud config proper
  application:
    name: first-service

  # Try to get reference to Config Server using service discovery.
  # To make it works, it's necessary to enable it first, and next
  # it's necessary to set the name of config server.
  cloud:
    config:
      discovery:
        enabled: true
        service-id: cloud-config-server
      # Stop the application if can't connect to config service
      fail-fast: true

# расположение eureka
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8083/eureka